language: erlang
otp_release:
  - R16B02
  - R16B01
  - R15B03
  - R15B02
  - R15B01
  - R14B04
  - R14B03
  - R14B02
notifications:
  email: false
  irc: "chat.freenode.net#xprous"
script: "make test"
